productPage:
  - hero:
    - image: /assests/image/hero.png #???
    - descrption: Hero description
  - journey Cards:
      - journeyCard:
        - title: Learn # => learn | Learning With Pavan => learning-with-pavan
        - description: 'Use our AI-powered portal to quickly discover the right integration for your next app project.
        
        Experiment with our API’s in our intelligent API Explorer. 
        
        Browse sample code and follow our guided tutorials to learn best practices for integration.'
        - link: 
          - type: markdown
          - uri: /docs/learn.md
        - contextualNavigationCards: #cnav card
          - contextualNavigationCard:
            - title: Getting Started
            - description: Let's start!
            - link: 
              - type: markdown
              - uri: /docs/getting-started.md
          - contextualNavigationCard:
            - title: Tutorials
            - description: Let's tut!
            - link: 
              - type: markdown
              - uri: /docs/tutorials.md
          - contextualNavigationCard:
            - title: Video
            - description: Watch
            - link: 
              - type: externalLink # [externalLink | internalLink | markdown]
              - uri: http://youtube.com/commercehub
      - journeyCard:
        - title: Build
        - description: 'Build on top of our sample code to get your app coded in minutes.
        
        Our lightweight SDK’s and plug-in’s might be the fastest path to completing your app.'
        - link: 
          - type: markdown
          - uri: /docs/build.md
        - contextualNavigationCards:
          - contextualNavigationCard:
            - title: SDKs
            - description: Free SDKs!!!
            - link: 
              - type: markdown
              - uri: /docs/sdks.md
          - contextualNavigationCard:
            - title: APIs
            - description: API me!
            - cardType: reference | page
            - link: 
              - type: internalLink
              - uri: /docs/api # => http://dev.fiserv.com/docs/api
      - journeyCard:
        - title: Test
        - description: 'Flex your app end-to-end in our full-featured Sandbox.
        
        Incorporate Sandbox testing into your CI pipeline.
        
        Use our intelligent Test Tracker to discover parts of your app that need more attention.
        
        
        *Requires registration'
        - link: 
          - type: markdown
          - uri: /docs/test.md
        - contextualNavigationCards: #cnav card
          - contextualNavigationCard:
            - title: API Reference
            - description: Let's start!
            - link: 
              - type: markdown
              - uri: /docs/getting-started.md
          - contextualNavigationCard:
            - title: SDKs
            - description: Let's tut!
            - link: 
              - type: markdown
              - uri: /docs/tutorials.md
          - contextualNavigationCard:
            - title: Sample Code
            - description: Watch
            - link: 
              - type: externalLink # [externalLink | internalLink | markdown]
              - uri: http://youtube.com/commercehub
      - journeyCard:
        - title: Deploy
        - description: 'When your app is ready for prime time, submit it for automated certification.
        
        Your certified app is now ready to be deployed to Production.
        
        Congratulations!
        
        
        *Requires registration'
        - link: 
          - type: markdown
          - uri: /docs/deploy.md
        - contextualNavigationCards:
          - contextualNavigationCard:
            - title: SDKs
            - description: Free SDKs!!!
            - link: 
              - type: markdown
              - uri: /docs/sdks.md
          - contextualNavigationCard:
            - title: APIs
            - description: API me!
            - cardType: reference | page
            - link: 
              - type: internalLink
              - uri: /docs/api # => http://dev.fiserv.com/docs/api
